### ISSUE TITLE
I installed the node and mongo, but always appear such mistakes. How to solve? Can you make a new version of the tutorial! thank you

### ISSUE THREAD

**Issue by laoyaoshine** [nedievas/zenbot#5]
I installed the node and mongo, but always appear such mistakes. How to solve? Can you make a new version of the tutorial! thank you

**Comment by laoyaoshine** [comment]
![qq 20170415125149](https://cloud.githubusercontent.com/assets/22680550/25060915/94d81f10-21db-11e7-8b35-42aeb9022606.png)

**Comment by nedievas** [comment]
I did not understand how you've got to that error. Start again.
See readme for tutorial. There should be no problem.
